# PostgreSQL Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=postgres
# Şifre güvenlik amacıyla Çevre Değişkeni (Environment Variable) olarak alınır:
spring.datasource.password=${DB_PASSWORD}

# Hibernate & JPA Ayarları (Tabloları otomatik oluşturur)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Uygulama Portu
server.port=8080
